
services:
  db:
    image: postgres:17.10-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER: ${APP_USER}
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: backend
    hostname: py-os
    working_dir: /app
    user: "${APP_UID}:${APP_GID}"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    
    command: tail -f /dev/null


configs:
  dbconfigfile:
    file: ./data-src.cnf
